### ISSUE TITLE
配置语言无效

### ISSUE THREAD

**Issue by lauheeliu** [calebman/vuepress-plugin-demo-container#12]
`plugins: {
        'demo-container': {
            locales: [
                {
                    "lang": "zh-CN",
                    "demo-block": {
                        "hide-text": "隐藏",
                        "show-text": "显示",
                        "copy-text": "复制",
                        "copy-success": "成功"
                    }
                },
                {
                    "lang": "en-US",
                    "demo-block": {
                        "hide-text": "Hide",
                        "show-text": "Show",
                        "copy-text": "Copy",
                        "copy-success": "Successful"
                    }
                }
            ] 
        }
    }`

**Comment by HenryTSZ** [comment]
@lauheeliu 重启服务, 在主页面强制刷新试试
