### ISSUE TITLE
按照格式写md 组件渲染不出

### ISSUE THREAD

**Issue by Venusjason** [calebman/vuepress-plugin-demo-container#3]
.vuepress/config.js
`plugins: ['demo-container']`

enhanceApp.js 与您源码配置一直

为什么组件无法渲染 只渲染出了代码片段

**Comment by calebman** [comment]
您好，有报错信息可以提供一下吗？

**Comment by calebman** [comment]
我修改了一个由于样式引用导致的问题，版本更新到 `0.1.1`，可以尝试一下这个版本是否解决了您的问题。

**Comment by calebman** [comment]
下方是一个示例代码包，已经运行通过，可作为参考。

[vuepress-demo-container-starter.zip](https://github.com/calebman/vuepress-plugin-demo-container/files/4877071/vuepress-demo-container-starter.zip)

**Comment by Venusjason** [comment]
非常感谢，已升级能够正常使用， 感谢作者
