### ISSUE TITLE
示例显示不全

### ISSUE THREAD

**Issue by ysg-lijinwen** [calebman/vuepress-plugin-demo-container#7]
配置vuepress的代码行号配置之后，左侧示例代码被行号遮挡。
![image](https://user-images.githubusercontent.com/5810737/90111798-b8d97480-dd81-11ea-899e-5bdf3584b1a9.png)

**Comment by calebman** [comment]
您好，问题已解决，请更新版本 0.2.0，参考提交：[fix(demoblock): solve the problem of code line number style](https://github.com/calebman/vuepress-plugin-demo-container/issues/4)

**Comment by ysg-lijinwen** [comment]
好的，非常感谢！

**Comment by ysg-lijinwen** [comment]
好的，非常感谢！

**Comment by ysg-lijinwen** [comment]
> 您好，问题已解决，请更新版本 0.2.0，参考提交：[fix(demoblock): solve the problem of code line number style](https://github.com/calebman/vuepress-plugin-demo-container/commit/675666eac7c20bc853be8b328b4b1134d91fa1af)

好的，非常感谢！
